FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /root

# install ORBSLAM3 ROS package

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y unzip pkg-config autoconf \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    # Use libvtk5-dev, libgtk2.0-dev in ubuntu 16.04 \
    libvtk7-dev libgtk-3-dev \
    libcanberra-gtk-module libcanberra-gtk3-module \
    libatlas-base-dev gfortran \
    libparmetis-dev \
    python3-wstool \
    # libtbb recommended for speed: \
    libtbb-dev \
    software-properties-common \
    git \
    build-essential \
    cmake \
    libeigen3-dev \
    python3-pip \
    libopencv-contrib-dev \
    gdb \
    zlib1g-dev \
    libopencv-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

RUN python3 -m pip install evo


RUN apt-get update && apt-get install -y libsuitesparse-dev libgl1-mesa-dev libglew-dev
 

RUN git clone https://github.com/stevenlovegrove/Pangolin.git && \
    cd Pangolin && \
    git checkout v0.6 && \
    mkdir build && cd build && \
    cmake .. && \
    make -j8 && make install